# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a68489a250cc98168cfda02694e027fd472291c14688c8ba734a5e04bbf636d08255c8ed245eabd60f6afbe9aaf3600cd64878fcbb6e92c1e379d392c598a2f2

test:
  secret_key_base: 798e30a74a9e58ddd041a421c9bfe141f7a80299e25ed065e969b42452c142e3308990aea03339bec83a21a3cd1b8c66a938f4e69cee05cafc8cdf187d97f3fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
